.\"
.\"  Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)
.\"
.\"	@(#)sl.1
.\"
.TH SL 1 "March 31, 2014"
.SH NAME
sl \- cure your bad habit of mistyping with a small dose of suffering
.SH SYNOPSIS
.B sl
[
.B \-alfcqse / \-ALFCQSE
]
.SH DESCRIPTION
.B sl
is a highly advanced animation program for curing your bad habit of mistyping "ls".
.SH OPTIONS
.TP
.B \-a/\-A
An accident is occurring. People cry for help.
.TP
.B \-l/\-L
Little version.
.TP
.B \-f/\-F
It flies like the galaxy express 999.
.TP
.B \-c/\-C
C51 appears instead of D51.
.TP
.B \-q/\-Q
It runs on overdrive.
.TP
.B \-s/\-S
It lags behind.
.TP
.B \-e/\-E
The program can be quit
.PP
.SH SEE ALSO
.BR ls (1)
.SH BUGS
It sometimes lists directory contents.
.SH AUTHORS
Toyoda Masashi (mtoyoda@acm.org), George Atkinson (github: GCPins)
